#![allow(
    clippy::float_cmp,
    clippy::missing_const_for_fn,
    clippy::trivially_copy_pass_by_ref,
    reason = "Exact float comparison intended; some f32 methods not const; &T API for non-Copy backend uniformity"
)]

use crate::int_math::IntType;

use alloc::string::String;
use core::cmp::Ordering;
use core::f32::consts::PI;

pub(in crate::float_ops) type BackingFloat = f32;

// ============================================================================
// Math bridge — libm (no_std) vs platform std math
// ============================================================================

macro_rules! math_bridge {
    ($(fn $name:ident($val:ident: f32) -> f32 = $libm:ident as $std:ident;)*) => {
        #[cfg(not(feature = "std"))]
        mod math {
            $(pub(super) fn $name($val: f32) -> f32 { libm::$libm($val) })*
            pub(super) fn atan2(y: f32, x: f32) -> f32 { libm::atan2f(y, x) }
            pub(super) fn pow(a: f32, b: f32) -> f32 { libm::powf(a, b) }
        }
        #[cfg(feature = "std")]
        mod math {
            $(pub(super) fn $name($val: f32) -> f32 { f32::$std($val) })*
            pub(super) fn atan2(y: f32, x: f32) -> f32 { y.atan2(x) }
            pub(super) fn pow(a: f32, b: f32) -> f32 { a.powf(b) }
        }
    };
}

math_bridge! {
    fn sin(x: f32) -> f32 = sinf as sin;
    fn cos(x: f32) -> f32 = cosf as cos;
    fn tan(x: f32) -> f32 = tanf as tan;
    fn asin(x: f32) -> f32 = asinf as asin;
    fn acos(x: f32) -> f32 = acosf as acos;
    fn atan(x: f32) -> f32 = atanf as atan;
    fn sinh(x: f32) -> f32 = sinhf as sinh;
    fn cosh(x: f32) -> f32 = coshf as cosh;
    fn tanh(x: f32) -> f32 = tanhf as tanh;
    fn asinh(x: f32) -> f32 = asinhf as asinh;
    fn acosh(x: f32) -> f32 = acoshf as acosh;
    fn atanh(x: f32) -> f32 = atanhf as atanh;
    fn exp(x: f32) -> f32 = expf as exp;
    fn expm1(x: f32) -> f32 = expm1f as exp_m1;
    fn ln(x: f32) -> f32 = logf as ln;
    fn log1p(x: f32) -> f32 = log1pf as ln_1p;
    fn sqrt(x: f32) -> f32 = sqrtf as sqrt;
    fn cbrt(x: f32) -> f32 = cbrtf as cbrt;
    fn floor(x: f32) -> f32 = floorf as floor;
    fn ceil(x: f32) -> f32 = ceilf as ceil;
    fn round(x: f32) -> f32 = roundf as round;
    fn fabs(x: f32) -> f32 = fabsf as abs;
}

// --- Precision control ---

pub(in crate::float_ops) const fn get_precision() -> u32 {
    24
} // f32 mantissa bits

// --- Construction & conversion ---

#[inline]
#[allow(
    clippy::cast_precision_loss,
    reason = "Lossy int-to-float; caller must restrict magnitude for exactness"
)]
pub(in crate::float_ops) fn from_int(value: &IntType) -> BackingFloat {
    *value as f32
}

#[inline]
pub(in crate::float_ops) const fn from_f32(value: f32) -> BackingFloat {
    value
}

#[inline]
#[allow(clippy::cast_possible_truncation, reason = "Lossy f64→f32 is intended")]
pub(in crate::float_ops) const fn from_f64(value: f64) -> BackingFloat {
    value as f32
}

#[inline]
#[allow(clippy::cast_precision_loss, reason = "Intended lossy conversion")]
#[allow(clippy::cast_possible_truncation, reason = "Lossy i64→f32 is intended")]
pub(in crate::float_ops) const fn from_i64(value: i64) -> BackingFloat {
    value as f32
}

#[allow(
    clippy::cast_precision_loss,
    reason = "i32::MAX is not exactly representable in f32; bounds check is approximate but safe"
)]
pub(in crate::float_ops) fn to_int(value: &BackingFloat) -> Option<IntType> {
    let v = *value;
    if v.fract() != 0.0 || v < i32::MIN as f32 || v >= i32::MAX as f32 {
        return None;
    }
    #[allow(
        clippy::cast_possible_truncation,
        reason = "Bounds just checked, f32→i32 is safe"
    )]
    {
        Some(v as i32)
    }
}

pub(in crate::float_ops) fn pi() -> BackingFloat {
    PI
}

pub(in crate::float_ops) fn nan() -> BackingFloat {
    f32::NAN
}

// ============================================================================
// Shared operations generated by macro
// ============================================================================

impl_shared_float_ops!();
