#![allow(
    clippy::float_cmp,
    clippy::missing_const_for_fn,
    clippy::trivially_copy_pass_by_ref,
    reason = "Exact float comparison intended; some f64 methods not const; &T API for non-Copy backend uniformity"
)]
use crate::int_math::IntType;

use alloc::string::String;
use core::cmp::Ordering;
use core::f64::consts::PI;

pub(in crate::float_ops) type BackingFloat = f64;

// ============================================================================
// Math bridge — libm (no_std) vs platform std math
// ============================================================================

macro_rules! math_bridge {
    ($(fn $name:ident($val:ident: f64) -> f64 = $libm:ident as $std:ident;)*) => {
        #[cfg(not(feature = "std"))]
        mod math {
            $(pub(super) fn $name($val: f64) -> f64 { libm::$libm($val) })*
            pub(super) fn atan2(y: f64, x: f64) -> f64 { libm::atan2(y, x) }
            pub(super) fn pow(a: f64, b: f64) -> f64 { libm::pow(a, b) }
        }
        #[cfg(feature = "std")]
        mod math {
            $(pub(super) fn $name($val: f64) -> f64 { f64::$std($val) })*
            pub(super) fn atan2(y: f64, x: f64) -> f64 { y.atan2(x) }
            pub(super) fn pow(a: f64, b: f64) -> f64 { a.powf(b) }
        }
    };
}

math_bridge! {
    fn sin(x: f64) -> f64 = sin as sin;
    fn cos(x: f64) -> f64 = cos as cos;
    fn tan(x: f64) -> f64 = tan as tan;
    fn asin(x: f64) -> f64 = asin as asin;
    fn acos(x: f64) -> f64 = acos as acos;
    fn atan(x: f64) -> f64 = atan as atan;
    fn sinh(x: f64) -> f64 = sinh as sinh;
    fn cosh(x: f64) -> f64 = cosh as cosh;
    fn tanh(x: f64) -> f64 = tanh as tanh;
    fn asinh(x: f64) -> f64 = asinh as asinh;
    fn acosh(x: f64) -> f64 = acosh as acosh;
    fn atanh(x: f64) -> f64 = atanh as atanh;
    fn exp(x: f64) -> f64 = exp as exp;
    fn expm1(x: f64) -> f64 = expm1 as exp_m1;
    fn ln(x: f64) -> f64 = log as ln;
    fn log1p(x: f64) -> f64 = log1p as ln_1p;
    fn sqrt(x: f64) -> f64 = sqrt as sqrt;
    fn cbrt(x: f64) -> f64 = cbrt as cbrt;
    fn floor(x: f64) -> f64 = floor as floor;
    fn ceil(x: f64) -> f64 = ceil as ceil;
    fn round(x: f64) -> f64 = round as round;
    fn fabs(x: f64) -> f64 = fabs as abs;
}

// --- Precision control ---

pub(in crate::float_ops) const fn get_precision() -> u32 {
    53
} // f64 mantissa bits

// --- Construction & conversion ---

#[inline]
#[allow(
    clippy::cast_precision_loss,
    reason = "Lossy int-to-float; caller must restrict magnitude to ≤ 2^53 for exactness"
)]
pub(in crate::float_ops) fn from_int(value: &IntType) -> BackingFloat {
    *value as f64
}

#[inline]
pub(in crate::float_ops) const fn from_f32(value: f32) -> BackingFloat {
    value as f64
}

#[inline]
pub(in crate::float_ops) const fn from_f64(value: f64) -> BackingFloat {
    value
}

/// Convert i64 to f64. Exact for |value| ≤ 2^53; loses LSB precision for larger magnitudes.
#[inline]
#[allow(
    clippy::cast_precision_loss,
    reason = "i64→f64 loses LSBs for |value| > 2^53; callers must accept this"
)]
pub(in crate::float_ops) const fn from_i64(value: i64) -> BackingFloat {
    value as f64
}

#[inline]
#[allow(
    clippy::cast_precision_loss,
    clippy::cast_possible_truncation,
    reason = "Precision loss and truncation are intentional for float-to-int conversions"
)]
pub(in crate::float_ops) fn to_int(value: &BackingFloat) -> Option<IntType> {
    (value.fract() == 0.0 && *value >= i64::MIN as f64 && *value < i64::MAX as f64)
        .then_some(*value as i64)
}

pub(in crate::float_ops) fn pi() -> BackingFloat {
    PI
}

pub(in crate::float_ops) fn nan() -> BackingFloat {
    f64::NAN
}

// ============================================================================
// Shared operations generated by macro
// ============================================================================

impl_shared_float_ops!();
